// Sion (LSGS) — Qualification Study Quiz · 40 questions from the Standard Operational Manual
// {q: question, a: [3 alternatives], c: index of the correct one (0-2)}
var QUIZ = [
 {q:"What is the only instrument approach available at Sion?",
  a:["The ILS RWY 25","The IGS RWY 25","The RNP RWY 07"], c:1},
 {q:"What is the glide path angle of the IGS 25 instrument segment?",
  a:["3.0\u00B0","4.5\u00B0","6.0\u00B0"], c:2},
 {q:"Where does the IGS 25 instrument segment end and the approach become visual?",
  a:["At D7.0 ISI","At D4.4 ISI, abeam the hospital","At the FAF ALETO"], c:0},
 {q:"What is the slope of the visual segment and of both PAPIs at Sion?",
  a:["3.0\u00B0","4.0\u00B0","4.5\u00B0"], c:1},
 {q:"What is the FAF of the IGS 25 and its crossing altitude?",
  a:["MASAB at 17,000 ft","GRANA at 17,000 ft","ALETO (D25.7 ISI) at 16,000 ft"], c:2},
 {q:"What are the GRANA holding limits?",
  a:["MHA 17,000 ft \u00B7 MAX FL240 \u00B7 MAX 220 KT","MHA 13,000 ft \u00B7 MAX FL180 \u00B7 MAX 230 KT","MHA 15,000 ft \u00B7 MAX FL200 \u00B7 MAX 210 KT"], c:0},
 {q:"What is the transition altitude at Sion?",
  a:["18,000 ft everywhere","17,000 ft, except 13,000 ft on all SIDs","10,000 ft, standard Switzerland"], c:1},
 {q:"What is the ATIS frequency and the associated rule?",
  a:["130.630 \u2014 monitoring compulsory","126.830 \u2014 monitor when MIL ON","121.705 \u2014 listen before start-up only"], c:0},
 {q:"For an IFR departure, start-up and ATC clearance are requested from:",
  a:["Sion Tower 118.275","Sion Ground 121.705","Sion Radar 126.830"], c:1},
 {q:"The LOC ISI final course is:",
  a:["250\u00B0, aligned with the runway axis","238\u00B0, offset south of the axis","244\u00B0, offset 6.5\u00B0 from the runway axis"], c:2},
 {q:"Inside D7.0 ISI the localizer is:",
  a:["Unreliable \u2014 use DME only","Accurate down to the threshold","Replaced by the glide path signal"], c:0},
 {q:"The LDA for RWY 25 is:",
  a:["1,940 m (6,365 ft)","2,000 m (6,562 ft)","2,060 m (6,758 ft)"], c:0},
 {q:"The PAPI RWY 25 beam is aimed:",
  a:["Along the runway axis","5\u00B0 north of the runway axis","2\u00B0 south of the runway axis"], c:1},
 {q:"Circling to RWY 07 at Sion is authorised for:",
  a:["Any category, day and night","CAT A/B/C, day only","CAT A and B only, MAX 125 kt, day only"], c:2},
 {q:"The G550 is certified approach category:",
  a:["CAT C \u2014 so the circling to RWY 07 is not available to it","CAT B when landing below 60,000 lbs","CAT D at all weights"], c:0},
 {q:"Can a CAT C aircraft use CAT B minima by flying at a light weight?",
  a:["Yes, if VREF stays below 121 kt on the day","Yes, with a one-off dispatch authorisation","No \u2014 only a permanent MLW reduction approved by the State of the Operator changes the category"], c:2},
 {q:"Who may fly the IFR procedures at Sion?",
  a:["Any IFR-rated crew with the charts on board","Only pilots, operators and aircraft holding the Sion airport qualification","Any crew, provided ATC approves on first contact"], c:1},
 {q:"For a Type A qualification, the IGS 25 minima are:",
  a:["DA 8,000 ft \u00B7 VIS 8,000 m + ceiling 6,500 ft AAL \u00B7 day only","DA per aircraft performance \u00B7 VIS 5,000 m \u00B7 day and night","RVR 550 m, day and night"], c:0},
 {q:"The night IGS 25 (Type B) additionally requires:",
  a:["EFVS and HUD operative","RVR 1,200 m and two qualified captains","High Performance departure capability and RWY 25 in use"], c:2},
 {q:"Aircraft performance requirements for the IGS 25 include:",
  a:["OEI ceiling 14,500 ft, ability to fly a 6\u00B0 GP, and the OEI missed-approach gradient","Steep-approach certification per EASA CS-25","RNP AR 0.1 capability"], c:0},
 {q:"Does the IGS 25 require steep-approach certification?",
  a:["Yes, because of the 6\u00B0 glide path","No \u2014 the IFR segment ends at 7 NM, but the aircraft must still be able to fly 6\u00B0","Only for night operations"], c:1},
 {q:"The G550 coupled FD/autopilot glideslope capability is limited to:",
  a:["Below 4.5\u00B0 \u2014 the 6\u00B0 segment is therefore hand-flown","6.5\u00B0, covering the IGS with margin","3.0\u00B0, standard ILS only"], c:0},
 {q:"The rate of descent on the 4\u00B0 visual segment is approximately:",
  a:["GS \u00D7 5.3 (120 kt \u2248 640 ft/min)","GS \u00D7 7.1 (120 kt \u2248 850 ft/min)","GS \u00D7 10 (120 kt \u2248 1,200 ft/min)"], c:1},
 {q:"On the RWY 25 visual segment, the left turn to the extended centreline begins:",
  a:["Immediately at D7.0 ISI","At D4.4 ISI, over Bramois","At D6.0 SIO, abeam St-L\u00E9onard (3.9 NM), passing just south of the hospital"], c:2},
 {q:"A go-around from the visual segment of the IGS 25 begins by:",
  a:["Flying to the runway first, then the published missed approach along the valley","An immediate climbing turn south towards GRANA","Holding over D7.0 ISI at 6,000 ft"], c:0},
 {q:"MIL ON at Sion is normally:",
  a:["Mon\u2013Fri 07:30\u201312:05 and 13:15\u201317:05 LT","H24 on working days","Weekends and Swiss public holidays"], c:0},
 {q:"The recommended arrival window at Sion is:",
  a:["Before 07:30 LT","12:05\u201313:15 LT \u2014 the midday MIL OFF gap","After 17:05 LT only"], c:1},
 {q:"If LSNPZ1 is active at your ETA:",
  a:["You only receive a CTOT delay","The airport closes to all traffic","The IFR flight plan to LSGS is rejected"], c:2},
 {q:"The AUP that shows LSNPZ1 activation is published:",
  a:["The day before, in the afternoon \u2014 and UUPs can still change it during the day","Exactly 2 hours before EOBT","Once a week, on Mondays"], c:0},
 {q:"Cancelling IFR to continue VFR below the TRAs (Y plan) should happen:",
  a:["Anywhere along the route","At FRIBU, BANKO, MOLUS, GEVEA, MOBLO or VENAT, within Geneva ACC","Only overhead GRANA"], c:1},
 {q:"North foehn at Sion means:",
  a:["West wind along the valley, RWY 25 in use","Calm wind and good visibility","East wind in the valley, RWY 07 in use, turbulence and windshear"], c:2},
 {q:"With foehn and RWY 07 in use, the IFR options for a CAT C G550 are:",
  a:["Land RWY 25 with tailwind within AFM limits, a visual to 07 after the IGS only in VMC, or divert","Fly the circling to RWY 07 at reduced speed","Request the RNP RWY 07 approach"], c:0},
 {q:"Runway de-icing at Sion in winter is the responsibility of:",
  a:["The airport administration \u2014 quick turnaround","The military base \u2014 expect delays","The handling agent, on request"], c:1},
 {q:"During snow clearing operations, rescue and fire fighting (RFF) is:",
  a:["Not available","Reduced to Cat 2","Doubled for the operation"], c:0},
 {q:"A High Performance (HP) departure at Sion means the aircraft can meet:",
  a:["3.7% to 12,500 ft after a VFR segment","13.3% up to 10,100 ft, all engines operating \u2014 RWY 25 only","12% OEI to 14,500 ft"], c:1},
 {q:"The Low Performance SID (SAPRE 1V) is:",
  a:["Available day and night from both runways","Reserved for turboprops","Day only \u2014 a VFR segment to GS300, then 3.7%; from RWY 25 it is CAT A/B only"], c:2},
 {q:"Compared with RWY 25, a G550 take-off from RWY 07 costs about:",
  a:["15,500 lbs of MTOW","The same weight \u2014 only the SID changes","5,000 lbs more available weight"], c:0},
 {q:"Holding at GRANA in icing conditions, the G550 speed is:",
  a:["The FMS maximum-endurance speed","200 KCAS, flaps UP (minimum 160 KCAS by limitation)","160 KCAS with flaps 10\u00B0"], c:1},
 {q:"Regarding EGPWS at Sion:",
  a:["TERRAIN INHIBIT must be ON below the MSA","The terrain display may be used to manoeuvre around terrain","There is no procedure to inhibit it for terrain \u2014 comply fully with cautions and warnings"], c:2},
 {q:"After a balked landing on RWY 07 with one engine inoperative, the analysed path is:",
  a:["A 180\u00B0 turn back to EOP 3 towards Martigny","Straight out on 070\u00B0 up the valley, minimum \u2248 10% gradient, joining track 064\u00B0 and climbing past GRANA","The visual circuit north of the field"], c:1},
];
